import Link from 'next/link';

export const metadata = {
  title: 'Legal — Dedrab',
  description: 'Terms of Use and Privacy Policy for Dedrab.',
};

export default function LegalPage() {
  return (
    <>
      <style>{`
        :root {
          --parchment: #F4EFE4;
          --linen: #EDE6D3;
          --forest: #0a3d2b;
          --forest-mid: #1a5c3f;
          --gold: #b8962e;
          --gold-light: #D4AF37;
          --umber: #2C1A0E;
          --warm-grey: #8a7e6e;
          --cream-dark: #d9cdb8;
        }
        body { background: var(--parchment); color: var(--umber); }
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Cormorant+Garamond:wght@300;400;500&family=DM+Sans:wght@300;400;500&display=swap');
        .legal-h2 {
          font-family: 'Playfair Display', serif;
          font-size: 28px;
          font-weight: 600;
          color: var(--forest);
          margin: 48px 0 16px;
          padding-top: 48px;
          border-top: 1px solid var(--cream-dark);
        }
        .legal-h2:first-of-type { border-top: none; padding-top: 0; margin-top: 0; }
        .legal-h3 {
          font-family: 'Playfair Display', serif;
          font-size: 18px;
          font-weight: 600;
          color: var(--forest-mid);
          margin: 28px 0 10px;
        }
        .legal-p {
          font-family: 'Cormorant Garamond', serif;
          font-size: 18px;
          line-height: 1.75;
          color: var(--warm-grey);
          margin: 0 0 14px;
        }
        .legal-ul {
          font-family: 'Cormorant Garamond', serif;
          font-size: 18px;
          line-height: 1.75;
          color: var(--warm-grey);
          padding-left: 24px;
          margin: 0 0 14px;
        }
        .legal-ul li { margin-bottom: 6px; }
        a.legal-link { color: var(--forest); text-decoration: underline; }
        a.legal-link:hover { color: var(--gold); }
      `}</style>

      {/* Nav */}
      <nav style={{
        background: 'var(--forest)',
        padding: '16px 60px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
      }}>
        <Link href="/" style={{ textDecoration: 'none' }}>
          <span style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 700, color: 'white', letterSpacing: 3, textTransform: 'uppercase' }}>Dedrab</span>
        </Link>
        <Link href="/design" style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 10, letterSpacing: 2.5, textTransform: 'uppercase', color: 'var(--gold-light)', textDecoration: 'none' }}>
          ← Back to Design Tool
        </Link>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: 780, margin: '0 auto', padding: '80px 40px 120px' }}>
        {/* Page heading */}
        <div style={{ marginBottom: 56 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, marginBottom: 16 }}>
            <div style={{ width: 32, height: 1, background: 'var(--gold)' }} />
            <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 10, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--gold)' }}>Legal</span>
          </div>
          <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 42, fontWeight: 400, color: 'var(--forest)', margin: '0 0 16px' }}>
            Terms &amp; Privacy
          </h1>
          <p style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: 19, color: 'var(--warm-grey)', lineHeight: 1.7 }}>
            Last updated: March 2025
          </p>
        </div>

        {/* ── TERMS OF USE ─────────────────────────────── */}
        <section id="terms">
          <h2 className="legal-h2">Terms of Use</h2>

          <h3 className="legal-h3">1. Acceptance of Terms</h3>
          <p className="legal-p">
            By accessing or using the Dedrab service at dedrab.com (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.
          </p>

          <h3 className="legal-h3">2. Description of Service</h3>
          <p className="legal-p">
            Dedrab is an AI-powered garden inspiration and design tool. You upload a photograph of your garden and receive a generated design proposal including plant suggestions, layout ideas, a visual render, and a cost estimate. The Service is provided for inspirational and planning purposes only.
          </p>

          <h3 className="legal-h3">3. Use of AI-Generated Content</h3>
          <p className="legal-p">
            All design proposals, plant lists, renders, cost estimates, and other outputs are generated by artificial intelligence. They are intended as inspiration and a starting point for your own planning. You acknowledge that:
          </p>
          <ul className="legal-ul">
            <li>AI-generated content may contain inaccuracies, errors, or suggestions unsuitable for your specific conditions.</li>
            <li>Plant suggestions may not be appropriate for your precise climate, soil type, or local regulations.</li>
            <li>Cost estimates are approximations only and should not be relied upon for budgeting without independent verification.</li>
            <li>Visual renders are artistic representations and will not match the precise final result of any physical garden work.</li>
          </ul>

          <h3 className="legal-h3">4. Your Content</h3>
          <p className="legal-p">
            You retain ownership of any photographs you upload. By uploading a photograph, you grant Dedrab a limited, non-exclusive licence to process the image solely for the purpose of generating your design proposal. We do not store your photographs beyond the duration of your session.
          </p>

          <h3 className="legal-h3">5. Acceptable Use</h3>
          <p className="legal-p">You agree not to:</p>
          <ul className="legal-ul">
            <li>Upload photographs containing people, minors, or content that is unlawful, harmful, or offensive.</li>
            <li>Attempt to reverse-engineer, scrape, or systematically extract data from the Service.</li>
            <li>Use the Service for commercial resale or distribution of generated content without our written consent.</li>
            <li>Misrepresent the AI-generated outputs as the work of a qualified landscape architect or professional.</li>
          </ul>

          <h3 className="legal-h3">6. Disclaimer of Warranties</h3>
          <p className="legal-p">
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied. We make no warranty that the Service will be uninterrupted, error-free, or that the outputs will meet your requirements. We do not warrant the accuracy, completeness, or suitability of any generated design proposal.
          </p>

          <h3 className="legal-h3">7. Limitation of Liability</h3>
          <p className="legal-p">
            To the fullest extent permitted by law, Dedrab and its operators shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Service or reliance on any AI-generated content. Our total liability to you for any claim arising out of your use of the Service shall not exceed the amount you paid, if any, to access the Service.
          </p>

          <h3 className="legal-h3">8. Professional Advice</h3>
          <p className="legal-p">
            Nothing in the design proposals generated by Dedrab constitutes professional landscape architecture, horticultural, structural, or legal advice. For significant garden projects, we recommend consulting a qualified landscape architect or garden designer.
          </p>

          <h3 className="legal-h3">9. Changes to Terms</h3>
          <p className="legal-p">
            We may update these Terms from time to time. Continued use of the Service after any changes constitutes your acceptance of the revised Terms. The date of the most recent revision is shown at the top of this page.
          </p>

          <h3 className="legal-h3">10. Governing Law</h3>
          <p className="legal-p">
            These Terms are governed by the laws of Ireland. Any disputes shall be subject to the exclusive jurisdiction of the courts of Ireland.
          </p>
        </section>

        {/* ── PRIVACY POLICY ───────────────────────────── */}
        <section id="privacy">
          <h2 className="legal-h2">Privacy Policy</h2>

          <h3 className="legal-h3">1. Who We Are</h3>
          <p className="legal-p">
            Dedrab (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) operates the garden design service at dedrab.com. This Privacy Policy explains how we collect, use, and protect information when you use our Service.
          </p>

          <h3 className="legal-h3">2. Information We Collect</h3>
          <p className="legal-p">When you use the Service, we may collect:</p>
          <ul className="legal-ul">
            <li><strong>Garden photographs</strong> — uploaded by you for the purpose of generating a design proposal. These are processed in real time and are not stored after your session ends.</li>
            <li><strong>Email address</strong> — provided voluntarily by you if you choose to receive your plan by email. Used solely to deliver your design plan and not added to any marketing list.</li>
            <li><strong>Usage data</strong> — standard server logs including IP address, browser type, and pages visited. Used for security, performance monitoring, and service improvement.</li>
            <li><strong>Approximate location</strong> — derived from your IP address to tailor plant suggestions and cost estimates to your region. We do not store precise location data.</li>
          </ul>

          <h3 className="legal-h3">3. How We Use Your Information</h3>
          <p className="legal-p">We use the information we collect to:</p>
          <ul className="legal-ul">
            <li>Generate and deliver your personalised garden design proposal.</li>
            <li>Send your plan to the email address you provide, if requested.</li>
            <li>Improve the accuracy and quality of the Service.</li>
            <li>Monitor and protect the security and integrity of the Service.</li>
          </ul>
          <p className="legal-p">
            We do not sell, rent, or share your personal information with third parties for marketing purposes.
          </p>

          <h3 className="legal-h3">4. Third-Party Services</h3>
          <p className="legal-p">We use the following third-party services to operate the Service:</p>
          <ul className="legal-ul">
            <li><strong>Google Gemini API</strong> — your garden photograph and design preferences are sent to Google&apos;s AI models to generate the design proposal. Google&apos;s data processing terms apply.</li>
            <li><strong>Cloudflare Turnstile</strong> — used to verify that requests come from real users. No personal data is stored by this check.</li>
            <li><strong>IP geolocation (ip-api.com)</strong> — used to determine your approximate region for plant and cost localisation. Only country and region data are used.</li>
          </ul>

          <h3 className="legal-h3">5. Data Retention</h3>
          <p className="legal-p">
            Uploaded photographs are not stored after your session. Email addresses provided for plan delivery are retained only long enough to send the email and are not stored in a marketing database. Server logs are retained for up to 30 days for security and diagnostic purposes.
          </p>

          <h3 className="legal-h3">6. Cookies</h3>
          <p className="legal-p">
            The Service does not use tracking cookies or advertising cookies. Session-level data may be held in browser memory during your visit but is not persisted beyond the session.
          </p>

          <h3 className="legal-h3">7. Your Rights</h3>
          <p className="legal-p">
            Under applicable data protection law (including GDPR where it applies), you have the right to request access to, correction of, or deletion of personal data we hold about you. Given that we do not persistently store personal data, most requests will be resolved immediately. To exercise any right, contact us at the address below.
          </p>

          <h3 className="legal-h3">8. Children&apos;s Privacy</h3>
          <p className="legal-p">
            The Service is not directed at children under the age of 16. We do not knowingly collect personal data from children. If you believe a child has submitted personal data through the Service, please contact us and we will take appropriate action.
          </p>

          <h3 className="legal-h3">9. Changes to this Policy</h3>
          <p className="legal-p">
            We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date. We encourage you to review this page periodically.
          </p>

          <h3 className="legal-h3">10. Contact</h3>
          <p className="legal-p">
            For any questions about these Terms or this Privacy Policy, please contact us at: <a href="mailto:hello@dedrab.com" className="legal-link">hello@dedrab.com</a>
          </p>
        </section>
      </main>

      {/* Footer */}
      <footer style={{ background: '#050f0a', padding: '28px 60px', textAlign: 'center' }}>
        <span style={{ fontFamily: "'DM Sans', sans-serif", fontSize: 10, color: 'rgba(255,255,255,0.25)', letterSpacing: 1 }}>
          © 2025 Dedrab · <Link href="/" style={{ color: 'rgba(255,255,255,0.35)', textDecoration: 'none' }}>Home</Link> · <Link href="/design" style={{ color: 'rgba(255,255,255,0.35)', textDecoration: 'none' }}>Design Tool</Link>
        </span>
      </footer>
    </>
  );
}
