import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal — Dedrab',
  description: 'Terms of Service and Privacy Policy for Dedrab.',
  alternates: { canonical: 'https://www.dedrab.com/legal' },
  robots: { index: true, follow: false },
};

const EFFECTIVE_DATE = '26 April 2026';

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[#F8F9F8]">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">

        <header className="mb-10">
          <p className="text-xs font-semibold tracking-widest uppercase text-[#b8962e] mb-3">
            Legal
          </p>
          <h1 className="font-serif font-extrabold text-[#0a3d2b] text-4xl md:text-5xl mb-4">
            Legal
          </h1>
          <p className="text-stone-500 text-sm">Effective date: {EFFECTIVE_DATE}</p>
        </header>

        <nav className="flex gap-6 mb-14 pb-6 border-b border-stone-200">
          <a href="#terms" className="text-sm font-semibold text-[#0a3d2b] underline underline-offset-2 hover:text-[#b8962e]">
            Terms of Service
          </a>
          <a href="#privacy" className="text-sm font-semibold text-[#0a3d2b] underline underline-offset-2 hover:text-[#b8962e]">
            Privacy Policy
          </a>
        </nav>

        {/* ─── Terms of Service ─── */}
        <section id="terms" className="scroll-mt-24 mb-20">
          <div className="prose prose-stone max-w-none
            prose-headings:font-serif prose-headings:font-bold prose-headings:text-[#0a3d2b]
            prose-h2:text-3xl prose-h2:mt-0 prose-h2:mb-6
            prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-3
            prose-p:text-[#1A1A1A] prose-p:leading-relaxed
            prose-a:text-[#0a3d2b] prose-a:font-medium prose-a:underline hover:prose-a:text-[#b8962e]
            prose-strong:text-[#1A1A1A]
            prose-li:text-[#1A1A1A]
            prose-hr:border-stone-200">

            <h2>Terms of Service</h2>

            <p>
              These Terms of Service govern your access to and use of Dedrab (the &quot;Service&quot;),
              operated by Dedrab (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By accessing or using the Service,
              you agree to be bound by these terms in full. If you do not agree, you must not use
              the Service.
            </p>

            <h3>1. What the Service Is</h3>
            <p>
              Dedrab is a garden design visualisation tool. It allows you to upload a photograph
              of your outdoor space and receive a computer-generated visual render, planting
              suggestions, a phased implementation guide, and a materials reference — collectively
              referred to as the &quot;Action Plan&quot;.
            </p>
            <p>
              The Service is currently available on an invite-only basis. Access requires a valid
              invite code issued by Dedrab.
            </p>

            <h3>2. What the Service Is Not</h3>
            <p>
              The Action Plan produced by Dedrab is a design visualisation and reference tool. It
              is not, and must not be treated as, professional landscape architecture advice,
              horticultural consultancy, structural engineering advice, or planning guidance of any
              kind.
            </p>
            <p>
              Dedrab makes no representation that any design, plant selection, material, or
              construction suggestion in an Action Plan is appropriate for your specific site
              conditions, soil type, microclimate, local planning regulations, or any other
              site-specific factor. All outputs should be reviewed by a qualified professional
              before implementation.
            </p>

            <h3>3. Your Responsibilities</h3>
            <p>By using the Service, you confirm that:</p>
            <ul>
              <li>You are 18 years of age or older.</li>
              <li>You have the right to upload the photographs and other content you provide.</li>
              <li>You will not use the Service for any unlawful purpose.</li>
              <li>You will not attempt to reverse-engineer, scrape, or otherwise misuse the Service.</li>
              <li>
                You will exercise your own judgement and, where appropriate, seek professional
                advice before implementing any suggestion generated by the Service.
              </li>
            </ul>

            <h3>4. Intellectual Property</h3>
            <p>
              <strong>Your content.</strong> You retain ownership of any photographs and content
              you upload. By uploading content, you grant Dedrab a limited, non-exclusive licence
              to process that content solely for the purpose of delivering your Action Plan. We do
              not use your uploaded images to train models or share them with third parties, except
              where required by our infrastructure providers to deliver the Service.
            </p>
            <p>
              <strong>Our content.</strong> The Service, including all software, design, text, and
              generated outputs (except your uploaded content), is owned by or licensed to Dedrab.
              Generated Action Plans are provided for your personal, non-commercial use only. You
              may not resell, redistribute, or commercially exploit any output of the Service
              without our prior written consent.
            </p>

            <h3>5. Limitation of Liability</h3>
            <p>
              To the fullest extent permitted by applicable law, Dedrab shall not be liable for
              any direct, indirect, incidental, consequential, or special loss or damage arising
              out of or in connection with:
            </p>
            <ul>
              <li>Your use of, or inability to use, the Service;</li>
              <li>
                Any reliance placed on the content of an Action Plan, including but not limited to
                plant selection, design layouts, materials specifications, or implementation
                guidance;
              </li>
              <li>
                Any costs, damages, or losses arising from the implementation of any design or
                suggestion generated by the Service;
              </li>
              <li>Any interruption, suspension, or termination of the Service.</li>
            </ul>
            <p>
              Where liability cannot be excluded by law, our total liability to you shall not
              exceed the amount paid by you (if any) for access to the Service in the twelve
              months preceding the event giving rise to the claim.
            </p>

            <h3>6. No Warranty</h3>
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranty of any kind,
              express or implied, including but not limited to warranties of merchantability,
              fitness for a particular purpose, or non-infringement. We do not warrant that the
              Service will be error-free, uninterrupted, or that any outputs will be accurate or
              suitable for your purposes.
            </p>

            <h3>7. Termination</h3>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time,
              with or without notice, including where we reasonably believe you have breached these
              terms.
            </p>

            <h3>8. Changes to These Terms</h3>
            <p>
              We may update these Terms of Service from time to time. Continued use of the Service
              after any change constitutes your acceptance of the revised terms. The effective date
              at the top of this page will reflect the date of the most recent update.
            </p>

            <h3>9. Contact and Support</h3>
            <p>
              If you have a question, concern, or support request, please use the contact form on
              our website. We do not accept requests by post or any other means.
            </p>

            <h3>10. Governing Law</h3>
            <p>
              These Terms of Service are governed by and construed in accordance with the laws of
              Ireland. Any dispute arising under or in connection with these terms shall be subject
              to the exclusive jurisdiction of the courts of Ireland.
            </p>

          </div>
        </section>

        <hr className="border-stone-200 mb-20" />

        {/* ─── Privacy Policy ─── */}
        <section id="privacy" className="scroll-mt-24">
          <div className="prose prose-stone max-w-none
            prose-headings:font-serif prose-headings:font-bold prose-headings:text-[#0a3d2b]
            prose-h2:text-3xl prose-h2:mt-0 prose-h2:mb-6
            prose-h3:text-xl prose-h3:mt-8 prose-h3:mb-3
            prose-p:text-[#1A1A1A] prose-p:leading-relaxed
            prose-a:text-[#0a3d2b] prose-a:font-medium prose-a:underline hover:prose-a:text-[#b8962e]
            prose-strong:text-[#1A1A1A]
            prose-li:text-[#1A1A1A]
            prose-hr:border-stone-200">

            <h2>Privacy Policy</h2>

            <p>
              This Privacy Policy explains how Dedrab collects, uses, stores, and protects personal
              data when you use the Service. We are the data controller for the purposes of the
              General Data Protection Regulation (GDPR) and the Irish Data Protection Acts 1988
              to 2018.
            </p>

            <h3>1. What Data We Collect</h3>
            <p><strong>Data you provide directly:</strong></p>
            <ul>
              <li>
                <strong>Photographs and site images</strong> — uploaded by you to generate an
                Action Plan.
              </li>
              <li>
                <strong>Invite code</strong> — used to verify your access to the Service.
              </li>
              <li>
                <strong>Support communications</strong> — any information submitted through our
                contact form.
              </li>
            </ul>
            <p><strong>Data collected automatically:</strong></p>
            <ul>
              <li>
                <strong>Analytics data</strong> — if you accept cookies, we collect anonymised
                usage data via Google Analytics 4, including pages visited and session duration.
                IP addresses are anonymised before processing. No personally identifiable
                information is passed to Google Analytics.
              </li>
              <li>
                <strong>Technical data</strong> — standard server logs including IP addresses,
                browser type, and access timestamps. Used for security purposes only.
              </li>
            </ul>

            <h3>2. How We Use Your Data</h3>
            <ul>
              <li>To deliver your Action Plan.</li>
              <li>To manage access to the Service via invite codes.</li>
              <li>To respond to support requests submitted through our contact form.</li>
              <li>
                To understand how the Service is used and improve it, where analytics consent
                has been given.
              </li>
              <li>To maintain the security and integrity of the Service.</li>
            </ul>
            <p>
              We do not use your data for advertising or profiling, and we do not sell your data
              to third parties.
            </p>

            <h3>3. Legal Basis for Processing</h3>
            <ul>
              <li>
                <strong>Contract performance</strong> — processing your images and delivering the
                Action Plan is necessary to fulfil the service you have requested.
              </li>
              <li>
                <strong>Legitimate interests</strong> — server logs and security monitoring are
                necessary to protect the Service and our users.
              </li>
              <li>
                <strong>Consent</strong> — analytics tracking is only activated where you have
                explicitly accepted cookies.
              </li>
            </ul>

            <h3>4. Third-Party Services</h3>
            <ul>
              <li>
                <strong>Supabase</strong> — database and storage, hosted within the EU (eu-west-1).
              </li>
              <li>
                <strong>Vercel</strong> — application hosting and delivery.
              </li>
              <li>
                <strong>Google Analytics 4</strong> — anonymised usage analytics, only where
                consent is given.
              </li>
              <li>
                <strong>Cloudflare</strong> — network security and delivery.
              </li>
            </ul>

            <h3>5. Data Retention</h3>
            <ul>
              <li>
                <strong>Uploaded photographs</strong> — deleted within 30 days of your last use,
                or immediately upon a valid deletion request.
              </li>
              <li>
                <strong>Support communications</strong> — retained for up to 12 months, then
                deleted.
              </li>
              <li>
                <strong>Server logs</strong> — retained for up to 90 days for security purposes.
              </li>
              <li>
                <strong>Analytics data</strong> — retained per Google Analytics default settings
                (14 months), where consent has been given.
              </li>
            </ul>

            <h3>6. Your Rights Under GDPR</h3>
            <p>You have the right to access, rectify, erase, restrict, or port your personal
            data, and to object to processing or withdraw consent at any time. To exercise any of
            these rights, please submit a request through the contact form on our website. We will
            respond within 30 days.</p>
            <p>
              You also have the right to lodge a complaint with the Data Protection Commission
              of Ireland at{' '}
              <a href="https://www.dataprotection.ie" target="_blank" rel="noopener noreferrer">
                dataprotection.ie
              </a>.
            </p>

            <h3>7. Cookies</h3>
            <ul>
              <li>
                <strong>Consent cookie</strong> — stores your analytics preference, valid for
                365 days.
              </li>
              <li>
                <strong>Google Analytics cookies</strong> — only set after explicit consent.
              </li>
            </ul>
            <p>
              We do not use advertising cookies, tracking pixels, or third-party marketing
              scripts. You can update your cookie preference at any time using the consent control
              on our website.
            </p>

            <h3>8. Data Security</h3>
            <p>
              We implement appropriate technical and organisational measures to protect your
              personal data, including HTTPS encryption in transit, access controls, rate
              limiting, and infrastructure hosted within the EEA.
            </p>

            <h3>9. Contact</h3>
            <p>
              For all enquiries, data subject requests, and support matters, please use the
              contact form on our website. For formal data protection correspondence, you may
              contact us at <strong>support@dedrab.com</strong>.
            </p>

            <h3>10. Changes to This Policy</h3>
            <p>
              We may update this Privacy Policy from time to time. The effective date at the top
              of this page reflects the date of the most recent revision.
            </p>

          </div>
        </section>

      </div>
    </div>
  );
}
