import { Document, Page, Text, View, Image, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF', fontFamily: 'Helvetica' },
  header: { marginBottom: 20, borderBottom: 1, borderBottomColor: '#164e63', paddingBottom: 10 },
  title: { fontSize: 24, color: '#164e63', letterSpacing: 1, textTransform: 'uppercase' },
  subtitle: { fontSize: 10, color: '#64748b', marginTop: 4, letterSpacing: 2 },
  imageContainer: { marginVertical: 20, overflow: 'hidden' },
  renderImage: { width: '100%', height: 300, objectFit: 'cover' },
  imagePlaceholder: { width: '100%', height: 60, backgroundColor: '#f1f5f9' },
  section: { marginTop: 15 },
  sectionTitle: { fontSize: 14, color: '#164e63', fontWeight: 'bold', marginBottom: 8, borderBottom: 0.5, borderBottomColor: '#e2e8f0', paddingBottom: 4 },
  content: { fontSize: 11, color: '#334155', lineHeight: 1.6 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 9, color: '#94a3b8', borderTop: 0.5, borderTopColor: '#e2e8f0', paddingTop: 10 }
});

interface Props {
  plan: string;
  imageBase64: string; // base64 data URL, e.g. "data:image/jpeg;base64,..."
  style: string;
}

export const GardenPlanPDF = ({ plan, imageBase64, style }: Props) => (
  <Document>
    <Page size="A4" style={styles.page}>

      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>GardenAI Design Specification</Text>
        <Text style={styles.subtitle}>
          LANDSCAPE ARCHITECTURAL PROPOSAL | STYLE: {style.toUpperCase()}
        </Text>
      </View>

      {/* AI Render Image — only shown if base64 data is available */}
      <View style={styles.imageContainer}>
        {imageBase64 ? (
          <Image src={imageBase64} style={styles.renderImage} />
        ) : (
          <View style={styles.imagePlaceholder} />
        )}
      </View>

      {/* Design Specification */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>PROJECT SCOPE & ANALYSIS</Text>
        <Text style={styles.content}>{plan}</Text>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by GardenAI Professional - Project Confidential
      </Text>

    </Page>
  </Document>
);
